### ISSUE TITLE
Ubuntu14.04软件源中的docker不支持exec参数

### ISSUE THREAD

**Issue by xuan880** [wppurking/ocserv-docker#11]
因为软件源中的版本不够新，不支持exec参数，如何修改用户？

**Comment by krizex** [comment]
试试进入docker的bash，然后执行ocpasswd呢

**Comment by xuan880** [comment]
试过，显示修改成功但是实际上ocpasswd文件没有变化。

**Comment by krizex** [comment]
升级docker吧。。。。
参考这个https://docs.docker.com/installation/ubuntulinux/

**Comment by wppurking** [comment]
请使用最新的 Docker , Ubuntu 官方源中的太老了.
