### ISSUE TITLE
docker 1.7 docker: "run" requires a minimum of 1 argument.

### ISSUE THREAD

**Issue by GreatFireWall** [wppurking/ocserv-docker#13]
[root@localhost ~]# docker run -d --privileged -v ~/ocserv-docker/ocserv:/etc/ocserv -p 443:443/tcp 
docker: "run" requires a minimum of 1 argument.
See 'docker run --help'.

Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

**Comment by wppurking** [comment]
@GreatFireWall 
`docker run -d --privileged -v ~/ocserv-docker/ocserv:/etc/ocserv -p 443:443/tcp wppurking/ocserv`
这个全命令.... 你在 REAME.md 中看漏了两个参数
