### ISSUE TITLE
替换证书失败

### ISSUE THREAD

**Issue by HamGuy** [wppurking/ocserv-docker#14]
你好。我参照您在 twitter 上的[回复](https://twitter.com/douglas_lee/status/590409745879568384)，按照这样的方式替换证书，但是执行了这句命令后，启动container失败。

```docker run -d --privileged -v ~/ocserv-docker/ocserv:/etc/ocserv -v ~/ocserv-docker/ssl:/opt/certs -p 5677:5677/tcp wppurking/ocserv```

` ~/ocserv-docker/ssl` 目录下存放的是我自己的SSL证书。

如果移除 ssl 证书挂载，则可以成功启动 container

还有，想请教下，为什么我进入 container 后，无法找到 `ocserv.conf` 这个文件，我的 `container` 内的`/etc/ocserv`目录是空的？

谢谢！

**Comment by trawor** [comment]
改证书名为`server-cert.pem`和`server-key.pem`
