### ISSUE TITLE
能否写一下在arukas.io上部署的教程？

### ISSUE THREAD

**Issue by luckypoem** [wppurking/ocserv-docker#21]
最近http://arukas.io这个免费的docker hosting很流行，你能否写一下在arukas.io上部署ocserv的教程？

非常感谢你

**Comment by wppurking** [comment]
无账户哈~ 申请中

**Comment by Indexyz** [comment]
arukas.io 好像是不支持tun设备的 所以是无法运行的
而且现在 Arukas Beta 已经结束支持了
