### ISSUE TITLE
ocserv.conf 文件错误, 导致 mac 客户端连接不上. 提示配置错误 The VPN configuration received from the secure gateway is invalid

### ISSUE THREAD

**Issue by njuaplusplus** [wppurking/ocserv-docker#6]
使用 mac 上的 any connect 4.0 报错 The VPN configuration received from the secure gateway is invalid.
原因是
ocserv.conf 中间第 444 以及 445 行 格式不对
https://github.com/wppurking/ocserv-docker/blob/master/ocserv/ocserv.conf#L444
https://github.com/wppurking/ocserv-docker/blob/master/ocserv/ocserv.conf#L445
应该是
route = 60.0.0.0/255.0.0.0
route = 63.0.0.0/255.0.0.0

修改之后就不报错了.

English translation:

On Mac, any connect 4.0 shows the error 'The VPN configuration received from the secure gateway is invalid'
It results from a bug in the ocserv.conf.
The route rules on line 444 and 445 in file ocserv.conf are misspelled.
It should be 
route = 60.0.0.0/255.0.0.0
route = 63.0.0.0/255.0.0.0

After the modification, the error disappears.

**Comment by wppurking** [comment]
oh my fault..

**Comment by wppurking** [comment]
fixed

**Comment by douglas-lee** [comment]
建议再加上
route = 0.0.0.0/128.0.0.0
route = 128.0.0.0/128.0.0.0
这样的话，连接上vpn以后，可以直连服务器，如果不加上这两条，ssh vpn服务器会连不上。不要问我为什么，这可以在网上查到解决方案，是ocserv比较奇怪的问题。

**Comment by njuaplusplus** [comment]
@douglas-lee 不需要的 我可以直接连接服务器 所以我觉得只要你的服务器不在之前那些route中就可以了

**Comment by wppurking** [comment]
我在想是否考虑使用 ocserv 的黑名单, 使用 no-route , 将国内那些不要 route 的 ip 添加进去, 其他的都默认路由到 ocserv
