### ISSUE TITLE
route 路由包含了 国内ip

### ISSUE THREAD

**Issue by njuaplusplus** [wppurking/ocserv-docker#7]
58.240.57.33 是南京的一个dns的地址.
https://github.com/wppurking/ocserv-docker/blob/master/ocserv/ocserv.conf#L442
这一句`route = 58.0.0.0/255.0.0.0`
使得使用这个dns 的用户在连接了 ocs 后, 上网不正常....

**Comment by wppurking** [comment]
路由部分参考: https://github.com/CNMan/ocserv-cn-no-route
我找个时间更新一下.
