### ISSUE TITLE
官网infradead.org都打不开了呢？

### ISSUE THREAD

**Issue by xyz12810** [wppurking/ocserv-docker#8]
昨天发现，官网infradead.org竟然打不开了！
是怎么回事啊？

**Comment by fangshili** [comment]
已经有几天这样了，但可以去这找到：http://pkgs.fedoraproject.org/repo/pkgs/ocserv/

**Comment by njuaplusplus** [comment]
恩 我修改了一下 dockerfile
[njuaplusplus/ocserv-docker](https://github.com/njuaplusplus/ocserv-docker)

**Comment by wppurking** [comment]
@njuaplusplus :+1:
