### ISSUE TITLE
docker run ... -p 443:443/tcp ... 似乎没有映射udp端口？

### ISSUE THREAD

**Issue by liudanking** [wppurking/ocserv-docker#9]

**Comment by wppurking** [comment]
是的, 默认没有映射 UDP.
那时候考虑没有映射 UDP, 是因为只有 TCP 的时候速度更快.
`docker run -d --privileged -v ~/ocserv-docker/ocserv:/etc/ocserv -p 443:443/tcp p 443:443/udp wppurking/ocserv`  开启 UDP 即可

**Comment by liudanking** [comment]
理论上，UDP会更快吧。不过我没有实际测试比较过。

**Comment by wppurking** [comment]
@liudanking [see this on twitter](https://twitter.com/litravis/status/500849945889349632)

**Comment by liudanking** [comment]
@wppurking 原来如此。估计an也用不了多久了

**Comment by wppurking** [comment]
说不准, 里面的原理都是 SSL, 按道理是没法监听沟通里面的信息的.
不过, 现在有的人用得很好, 有的人一连就断, 也只能猜测原因..

**Comment by liudanking** [comment]
我现在开启了UDP，没有断开的情况。先观察看看

**Comment by wppurking** [comment]
@liudanking :+1:
